### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by Mad7eo** [phenomen/flc#11]
I really like the idea of a lightweight browser just for foundry but I can't use it

![image](https://user-images.githubusercontent.com/89466389/231080286-d0ef8f72-f69b-4a59-9098-9a179d4e2b56.png)

I haven't got this problem on chrome or firefox, what can I do?

**Comment by phenomen** [comment]
Looks like your app uses integrated Intel GPU instead of your Nvidia/AMD GPU.

This bug with white "ladder" is caused by an outdated Intel driver. You may update your driver by downloading this tool: https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html

But even after you do that, it's better to force FLC to use your proper GPU (you may do that in NVIDIA Control Panel).
